#!/usr/bin/env node
require('babel/register')({
  plugins: ['babel-plugin-rewire']
})

var log = require('npmlog')
log.addLevel('show', 10000, {}, '>')

var glob = require('glob')
glob.sync(
  process.argv[2] || '{**/,}*-test.js',
  {cwd: 'test'}
)
.forEach(function (filename) {
  require('./' + filename)
})
