#!/usr/bin/env node
require('babel/register')({
  plugins: ['babel-plugin-rewire']
})

var log = require('npmlog')
log.addLevel('show', 10000, {}, '>')
log.level = 'silent'

require('require-all')({
  dirname: process.cwd() + '/test',
  filter: process.argv[2] || /\-test\.js/,
  recursive: true
})
